### ISSUE TITLE
[Linux] After a second run it stops loading

### ISSUE THREAD

**Issue by PhaserEditor2D** [PhaserEditor2D/PhaserEditor#10]
Sometimes the editor stops loading in Linux.

We don't know the reason yet but the problem is related to restore the previous workbench state. When you close the editor it saves the state to the workspace. This state contains some information like the opened editors and views.

To get the editor to open, you should make it to load without restore this state, so you have two options:

* Execute the editor with the `-clearPersistedState` option, to clear the state and start with a fresh workbench.
```
./PhaserEditor -clearPersistedState
```
* Execute the editor with the `-persistState false` option. In this way the editor will not save the state when it is closed:
```
./PhaserEditor -persistState false
```

If you want to make this options by default, edit the `PhaserEditor.ini` file and add the following at the end:

```
persistState=false
clearPersistedState=true
```

We recommend to do both things, clear the state at the startup and disable the state saving at the closing.

Thanks to @samsstuff for report and try to fix this issue.

References: *How can I prevent my workbench model from being saved on exit?* https://wiki.eclipse.org/Eclipse4/RCP/FAQ

**Comment by samsstuff** [comment]
Hey Arian I made a simple quick bash script to put on my desktop so I won't have to keep typing it in, lazy man way to load it lol


for others that want to do this and don't know how, open a text editor (leafpad or whatever you use)

paste this into it:

#/bin/bash
/home/yourhomefolder/PhaserEditorNew/PhaserEditor -clearPersistedState

save as and name it loadPhaser.sh or whatever you want with .sh at the end
right click it give allow execution as program under permissions
just make it a direct link to where you have the phaser bin file at
place it on your desktop or where ever you want that way you don't have to repeat the terminal loading and just double click it as a normal icon and run it 
Quick and simple
Hope it makes it easier for the linux crowd
Sam

**Comment by boniatillo-com** [comment]
Thanks @samstuff

I keep looking for the reason of the problem, as soon as I find it I will upload an update.

**Comment by samsstuff** [comment]
no problem I'm still looking into it myself, seems to be an error with quite a few folks with different versions of eclipse.
I've been looking into the log file again
Loading extension: org.eclipse.fx.osgi
	eclipse.properties not found
also
/.options not found
might be another clue, I'll keep looking also.

At least the temp fix works great for now and is as good as it can get, we only have to reopen the js files, no big deal for that one.

**Comment by boniatillo-com** [comment]
Not happening anymore for the new version. In any case we are going to release a preview that will be available to test this issue.

**Comment by samsstuff** [comment]
cool, I'll give it a try when ready, I'm using Manjaro arch base linux now so if it works on this it should work on all.
Sam

**Comment by boniatillo-com** [comment]
Now for version 1.4.1 the option `-persisteState false` will be used by default in Linux so the user do not have to set it. The drawback is that the editor is not going to "remember" the last opened editors and views.

Yet we do not find the way to avoid the real bug.

**Comment by samsstuff** [comment]
works good, tested it on manjaro xfce, no issues except remembering which is no big deal at all, a couple of clicks open the pages needed.

Thanks for the update Arian

**Comment by PhaserEditor2D** [comment]
Now I am working on linux so linux users will get a better product :)

I will close this, I think this is not happening anymore since we updated to Eclipse Oxygen.
