### ISSUE TITLE
Mathematical operations in fields

### ISSUE THREAD

**Issue by sathyarajshetigar** [PhaserEditor2D/PhaserEditor#101]
Hi,
   Please add the capability to include mathematical operation in inspector fields
example:
https://www.youtube.com/watch?v=XeKewRQRB90

![capture](https://user-images.githubusercontent.com/42057975/51360732-e6e9ca80-1af2-11e9-9b78-0733a72e5ecc.PNG)

**Comment by RANUX** [comment]
And increase/decrease +1/-1 then pressing up/down arrows in input field or then shift pressed with up/down do do increase/decrease: +10/-10
Thanks!)

**Comment by PhaserEditor2D** [comment]
In v1 of the editor we did it, you can write JavaScript expressions in the fields. We can do this same here. 

https://phasereditor2d.com/docs/canvas.html#object-properties

**Comment by PhaserEditor2D** [comment]
Done, now you can write JavaScript expressions in the Properties fields. Even, you can use the `Math` class. To evaluate the expressions we use the Nashorn script engine (like in v1 of the editor).

@RANUX I created a second issue for the up/down arrows: https://github.com/PhaserEditor2D/PhaserEditor/issues/104
