### ISSUE TITLE
pack.json not found -> MISSING ASSET

### ISSUE THREAD

**Issue by Thaval** [PhaserEditor2D/PhaserEditor#106]
Hi,

I recently imported the project from a colleague to continue to work with the new files. But, unfortunately, the Phaser Editor cannot seem to find the pack.json file, therefore all assets within the canvas files cannot be rendered because it says MISSING ASSET. The key is correct, the sections are correct.. at the right side (within the asset window), actually the pack folder should not be empty, right? But it is. 
The interesting thing is that the game works fine and all assets are loaded when I start the project.
I only opened the WebContent folder, so this is my root folder within the project explorer. The location of the pack.json is WebContent/assets/pack.json.

What am I missing? I dont want to exchange all textures for the assets by hand because they are so many... this would take hours or even days. Can you suggest me a more time saving opportunity?

Edit: When I open a canvas file and go to the configuration tab -> state -> pack, there's no pack listed either.

Edit2: Stupid me. I opened the wrong folder ... I had to open the parent folder of WebContent to load everything correctly. This was not clear to me because I didn't see the hidden ".settings" folder. This issue was only an user issue, can be closed straight away.

**Comment by PhaserEditor2D** [comment]
Hello @Thaval

I am glad it is working for you now.
