### ISSUE TITLE
[Paid User] Add Scale Manager parameters to game config

### ISSUE THREAD

**Issue by sathyarajshetigar** [PhaserEditor2D/PhaserEditor#108]
Please add the scale manager configs to the project wizard.
https://madmimi.com/p/8ee19d

**Comment by PhaserEditor2D** [comment]
Done

In the Project wizard you can set the scale mode and autoCenter. There are more parameters about the scale manager, but I think it is not good to list all of them in that wizard. Later, we will create a `gama.json` file to generates all the game configs.

![image](https://user-images.githubusercontent.com/12187299/53291673-19878280-3785-11e9-8790-b0a07c6da2d3.png)
