### ISSUE TITLE
Some files are not served to browser

### ISSUE THREAD

**Issue by Thaval** [PhaserEditor2D/PhaserEditor#109]
## Version

* Phaser Editor Version:  1.5.3

* Operating system: Windows 10

## Description

When the game is started from the Phaser Editor, a new Browser opens up and some Javascript files are missing in the source (Google Chrome). Though, the game still works as the "missing" Javascript files are hosted by VM. But I cannot debug the JS code.

(Maybe that's only some configuration? I don't know. I check the settings and everything looked clean).

**Comment by PhaserEditor2D** [comment]
Do you have all your files under the WebContent folder? An image of your errors could help.

**Comment by Thaval** [comment]
Sure. There is no error. But I can't find some files (CTRL + O in DevTools to find a file by name) and the source of console logs are VM:XXX where XXX is a random number.

**Comment by PhaserEditor2D** [comment]
Are you loading the files by demand? I you load the JS files using the pack.json file, then the files are loaded by demand, when you load the section of the pack.

**Comment by PhaserEditor2D** [comment]
Hi @Thaval, are you yet experiencing this issue?

**Comment by Thaval** [comment]
Yea still. Sorry, I forgot to answer your question. I included "//@ sourceURL=foo.js" at the bottom of the javascript files that were only loaded anonymously.

**Comment by PhaserEditor2D** [comment]
Hi @Thaval . Please, can you reproduce that behavior in a very small project, so you can send it to us and we can see what's happening?

**Comment by Thaval** [comment]
I'm sorry, I can't seem to reproduce it... If I remember correctly, then this appeared after I had mistyped a shortcut. But I couldn't find any setting which had been changed since then. Excuse me. If I'm the only one having this trouble, then it seems to be an user issue or at least a bug that appears so rarely that's it not worth investigating on it. Do you agree?

**Comment by PhaserEditor2D** [comment]
Hi @Thaval, we can reopen the issue if it appears again. Thanks very much for your contribution. Feel free to open new issues if you find something.
