### ISSUE TITLE
Characters color blends poorly with background in Dark Theme (OS Windows) v2

### ISSUE THREAD

**Issue by RANUX** [PhaserEditor2D/PhaserEditor#110]
## Version
* Phaser Editor Version: v2
* Operating system: Windows 7

## Description
Characters color blends poorly with background in Dark Theme (Editor windows: Outline, Assets, Pack)
How can i fix this? Thanks!
![2019-02-23_18-01-08](https://user-images.githubusercontent.com/1157667/53288254-4e9cd080-3797-11e9-9098-ec4a55067b14.png)

**Comment by PhaserEditor2D** [comment]
Dark themes are not well supported yet, but I will take a look because for Windows it can work.

**Comment by PhaserEditor2D** [comment]
Done

![image](https://user-images.githubusercontent.com/12187299/53292634-46db2d00-3793-11e9-8250-46051414b281.png)
