### ISSUE TITLE
[Paid User] Add a field to set the name of the sprite

### ISSUE THREAD

**Issue by sathyarajshetigar** [PhaserEditor2D/PhaserEditor#111]
Please add a field to set the name of the sprite which calls `setName(value)` or a tick mark to use the same variable name as the name of the gameObject.

**Comment by PhaserEditor2D** [comment]
Check the **Name** field to use the same value of the **Variable Name** field:

![image](https://user-images.githubusercontent.com/12187299/53578153-10abfd80-3b45-11e9-8e44-337d05332400.png)
