### ISSUE TITLE
[Paid user] One click bundling of the project

### ISSUE THREAD

**Issue by sathyarajshetigar** [PhaserEditor2D/PhaserEditor#113]
Is it possible to bundle the game with parcel or webpack within the editor? If possible please add that as a feature

**Comment by PhaserEditor2D** [comment]
We think the editor is flexible enough to allow users to use webpack, parcel or other build/packing system, but you should do it manually. The JavaScript echosystem is huge and there are lot of frameworks that do "the same thing", that right now we do not plan to support a particular build framework. There are a lot of thing to do related to Phaser that have more priority.
