### ISSUE TITLE
Automatic updates MacOS v2.0.1

### ISSUE THREAD

**Issue by RANUX** [PhaserEditor2D/PhaserEditor#114]
## Version
* Phaser Editor Version: 2.0.1
* Operating system: MacOS Mojave

## Description
Hi! I've got `Insufficient access privileges to apply this update.` message and i couldn't continue install update :( On which folders i should change privileges mode?
Thanks!
<img width="872" alt="screenshot 2019-03-04 at 01 18 23" src="https://user-images.githubusercontent.com/1157667/53702837-5eae5300-3e1c-11e9-84c5-1f5138145043.png">

**Comment by PhaserEditor2D** [comment]
Hi,

Please, try by moving the Phaser Editor installation folder to a common user folder, like the Desktop or Documents. Then try again.

Googling for Eclipse users with the same problem I found this answer (you replace Eclipse.app for PhaserEditor2D.app):

```
Hit same problem on Macos sierra 10.12.3 after clean install of Eclipse JEE Neon R. A clue was that my mac showed a dialog when I launched the app that asked:

“Eclipse.app” is an application downloaded from the Internet. Are you sure you want to open it?
When the updater dialog box showed "Insufficient access privileges to apply this update" I checked the Eclipse.app directory (I had downloaded & unpacked the .tar.gz file, if that matters) and saw this:

 drwxrwxr-x@  3 chris  staff         102 Jun 13  2016 Eclipse.app
I examined the extended attribute and saw this:

$ xattr Eclipse.app
com.apple.quarantine
That quarantine attribute seems to block the Eclipse updater! I removed that extended attribute like this:

xattr -d -r Eclipse.app

After that Eclipse updated itself very happily. HTH
```

**Comment by RANUX** [comment]
Command:
```
sudo xattr -r -d com.apple.quarantine PhaserEditor2D.app
```
resolved issue.

**Comment by PhaserEditor2D** [comment]
Great.
