### ISSUE TITLE
Spelling mistake on Atlas Generator Tool tip

### ISSUE THREAD

**Issue by bfountaine** [PhaserEditor2D/PhaserEditor#118]
## Version

* Phaser Editor Version: Phaser Editor 1.5.3.20181107

* Operating system: Windows 10

## Description

Create or open an atlas file, the tooltip when you hover your mouse over the button that toggles the left side panel has a spelling mistake, it says legft rather than left.
![bug](https://user-images.githubusercontent.com/49424711/55846785-0b59be00-5b9b-11e9-9bf2-810b5d687fa4.png)

**Comment by PhaserEditor2D** [comment]
Done, will be included in 1.4.5 very soon.
