### ISSUE TITLE
No right click menu

### ISSUE THREAD

**Issue by zombiestruck** [PhaserEditor2D/PhaserEditor#122]
## Version

* Phaser Editor Version: 3.16.2

* Operating system: Windows 10

## Description

Right-click menu isn't there. Can't use transform to adjust scales. I'm fairly new, so I could just be doing something wrong.

## Possible solution

EDIT: By default, the properties window isn't open. You have to open it in: 
window -> Show View -> Other -> General -> Properties. This allows you to do things like transform but still lacks significant features for ease of use.
Can this be opened by default in future updates? Would have made life a lot easier.

**Comment by PhaserEditor2D** [comment]
Hi, the window Properties is open by default. Maybe you closed it before. You can always right-click on the Phaser perspective button and select Reset.

![image](https://user-images.githubusercontent.com/12187299/57015062-d3192e80-6be0-11e9-863e-21708726141f.png)


That version of the editor is in Preview mode. Please, you can create a new issue for each feature is missing and we will add it to the TODO list. Thanks.

**Comment by zombiestruck** [comment]
Thanks for the quick reply! Just submitted the feature request.
