### ISSUE TITLE
BitmapText item doesn't display in the right place when re-opening canvas file

### ISSUE THREAD

**Issue by bfountaine** [PhaserEditor2D/PhaserEditor#124]
## Version

* Phaser Editor Version: 1.5.3.20181107

* Operating system: Windows 10

## Description

When you create a BitmapText object and add it to a canvas, set the position, size, anchor, tint etc, save canvas, close then re-open the canvas, the BitmapText doesn't display in the right place or show the tint. If you click on the text and then try and drag it, it will jump to the correct position and then drag from there, so it does hold it's properties, it just doesn't display correctly on first re-open of the file. As soon as you try and interact with the element it reverts to as it should be though. I think it may have something to do with setting the anchor on the element but am unable to consistently reproduce it sorry. Screen shots attached so you can see. As you can see, the properties on both are identical, but the rendering is off.
correct view: (how it looks when I save and close the canvas file)
![bitmaptext correct](https://user-images.githubusercontent.com/49424711/57053017-502acd80-6cdf-11e9-83dc-cf69b9d160aa.png)
incorrect view (how it looks when I re-open the canvas file)
![bitmaptext incorrect](https://user-images.githubusercontent.com/49424711/57053018-5325be00-6cdf-11e9-8193-1e2908553ec3.png)

**Comment by PhaserEditor2D** [comment]
Done, will be included in 1.4.5 very soon.
