### ISSUE TITLE
Update fails on unexpected checksum

### ISSUE THREAD

**Issue by ehnolte** [PhaserEditor2D/PhaserEditor#125]
I just tried to update from  v2.0 to the latest 2.1 but get an error on an incorrect checksum:
An error occurred while collecting items to be installed
session context was:(profile=profile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Problems downloading artifact: osgi.bundle,phasereditor.atlas.core,2.0.3.20190320.
SHA-256 hash is not as expected. Expected: e300751eba05ce729afb8d4c06ca36629a4089bb4388b673e5ae27721568581e and found 9763ec758f63f987122bd63be33b243f543e7d6fb3717e800563a9334f2d4a85.
Problems downloading artifact: osgi.bundle,phasereditor.atlas.ui,2.0.3.20190320.
SHA-256 hash is not as expected. Expected: 14176f785a933adfedfb865899d4a8ac4aec41ede58b64c2af2c41680cd6fd39 and found a84e890627d67520f9ecfd4cfd7942d2f1541573d260b25f0ccc0b0eae65d83e.

**Comment by PhaserEditor2D** [comment]
Hi. What's your OS?

Can you try to update again? It looks like a corrupted download.

**Comment by ehnolte** [comment]
Hi 
I have Macos 10.14.4

interestingly enough, when I restart, the splashscreen says v2.1.0 and phaser 3.17, 
but in the botton of the application window it says v2.0.2 and v3.16.2 

I tried updating again with the same error.


Regards

On 2 June 2019 at 12:34:17, Phaser Editor (notifications@github.com) wrote:

Hi. What's your OS?

Can you try to update again? It looks like a corrupted download.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

Ernst Nolte


+31 6 813 28 775
ernst@geckotech.nl
www.geckotech.nl
Laan van Kronenburg 14, 1183 AS, Amstelveen

**Comment by PhaserEditor2D** [comment]
Ok thanks.

**Comment by PhaserEditor2D** [comment]
Hi. This is happening when you update for a version previous to 2.0.3. We realized that old modules with the same version/name have a different checksum. This should be fixed now. Please try the update again.

By the way, don't miss to read the Migration Guide for the last version: https://phasereditor2d.com/blog/2019/05/phaser-editor-210-released#migration-guide

Thanks
Arian

**Comment by ehnolte** [comment]
Thanks - it works now.
