### ISSUE TITLE
I noticed the GPU went loco with PhaserEditor

### ISSUE THREAD

**Issue by j2l** [PhaserEditor2D/PhaserEditor#127]
## Version
* Phaser Editor Version: 2.1.1
* Operating system: Windows 10 Pro

## Description
I'm evaluating your solution but have multiple questions:
First, I noticed the GPU went loco with PhaserEditor. Like if a bitcoin mining was running 😄 
Do you know why?
![image](https://user-images.githubusercontent.com/65325/60503364-d81d5b80-9cbf-11e9-9fd1-1c928eb652c0.png)

Let's say it was not the smoothest experience.

**Comment by PhaserEditor2D** [comment]
Hi, thanks for reporting these bugs, I created separate issues:

https://github.com/PhaserEditor2D/PhaserEditor/issues/128

https://github.com/PhaserEditor2D/PhaserEditor/issues/129

**Comment by PhaserEditor2D** [comment]
Please, can you tell me the editors open when the GPU gets like that?

Does it happen always? With few images?

**Comment by j2l** [comment]
I just noticed the GPU fan started. 
I wasn't doing anything special. Very few images (from Flying Dragon).

I exited and relaunched PhaserEditor and it worked normally (high CPU at first, and some GPU when dragging an image then 1% when idle).
I don't know what happened but it was stable in pumping resources, enough time to do a screenshot.

**Comment by PhaserEditor2D** [comment]
I should create some preferences to disable the screenshot builders, them could be the reason. The first time you create a project it creates the screenshots, the second time it reuses them. Please, can you try to create a completely new project again, with the Flying dino template and confirm the GPU gets a high usage percent?

**Comment by j2l** [comment]
OK, I took some time to pin the problem and made an (unpublished) video:
https://youtu.be/YetmsVP7MWo
Note that if I hadn't removed the watermelon animation, it would still use 80% GPU after minutes (and the GPU fan kicks in), so I suspect a glitch somewhere.

My GPU is GTX 970. so 80% is a lot of resources for a 2D platformer.

**Comment by PhaserEditor2D** [comment]
Thanks very much for the video! I am on it. Please send me hello to developers@phasereditor2d.com

**Comment by PhaserEditor2D** [comment]
I think this is related to the embedded browser or how we are using Phaser in it. This will take some time. I keep you updated.

**Comment by PhaserEditor2D** [comment]
Hi, I received your email but the reply was rejected. You can PM in twitter https://twitter.com/PhaserEditor2D

**Comment by j2l** [comment]
Hmm, thanks.
It means I might have issues with my DMARC settings.

**Comment by PhaserEditor2D** [comment]
Please, can you try to reproduce the same behavior and then Refresh the browser? It looks like Phaser gets into a lot of requestAnimationFrame.
![image](https://user-images.githubusercontent.com/12187299/60605593-d15a1b80-9d87-11e9-8c7b-2c09210e4650.png)

**Comment by j2l** [comment]
I was learning more about PhaserEditor when I see this ticket and noticed that GPU was low but CPU was high.
I hit refresh and CPU went down. So I guess, it's a fix for now.
Really hope it will be automatic :)

**Comment by PhaserEditor2D** [comment]
Hi, thanks for testing it.

I will reopen the issue because yet I don't realize what is going with Phaser and the browsers.

**Comment by PhaserEditor2D** [comment]
I think I found the problem. The common is that Phaser runs a paint loop with a high FPS. We, in Phaser Editor, stop that loop and request a paint just when needed. For I reason I should find now, when you drop an object, the loop may start again and a lot of painting are requested and never stop.
I should release a new version as soon as I fix the problem.

**Comment by PhaserEditor2D** [comment]
Some progress on this.

The problem is that when you add a new texture, the editor has to start the Phaser loader to load it. For some reason, it starts the game loop, and we do not stop it at time. Please, uncompress the zip [I attach here](https://github.com/PhaserEditor2D/PhaserEditor/files/3356627/patch.zip) and paste its content into the folder:

``PhaserEditor2D/plugins/phasereditor.scene.ui.editor.html_2.1.1.20190623/html/out``

Accept to replace the files.

You should look a white label in the left corner of the Scene Editor. That label displays the number of painting calls. Please, try to reproduce the error and see that number does not go crazy and go up forever, even if the editor is idle.

If it works for you, I should release a new version of the editor this week, with the fix.

Thanks

![image](https://user-images.githubusercontent.com/12187299/60620633-b6989e80-9da9-11e9-80eb-964403124741.png)

**Comment by j2l** [comment]
OK, the initial drag problem [seems fixed](https://youtu.be/9oZLFgukZ74) but now, when I start and do nothing, it seems to hold the CPU in hostage until I refresh the internal browser.

It's a slightly different problem since it's the CPU and the painting calls remain under 21 on idle.

I write another ticket for issue with selection behavior

**Comment by PhaserEditor2D** [comment]
>  when I start and do nothing, it seems to hold the CPU in hostage until I refresh the internal browser.

I will try to reproduce that behavior.

>  the painting calls remain under 21 on idle.

That's the correct behavior. The painting calls should increment only when you do modifications in the scene and it needs to be repainted.
