### ISSUE TITLE
Pack.json copyright

### ISSUE THREAD

**Issue by PhaserEditor2D** [PhaserEditor2D/PhaserEditor#128]
(reported by @j2l)

## Version

* Phaser Editor Version: 2.1.1
* Operating system: Windows 10 Pro

## Description

I followed your tutorial and started a new project, with an empty pack.json and in pack.json file, I see: `    "copyright": "Arian Fornaris (c) 2015,2019"`, why?
Do we have to give copyright on our assets and games to you?
Or do you hold copyright on the pack.json file?

**Comment by PhaserEditor2D** [comment]
@j2l please follow this.

**Comment by PhaserEditor2D** [comment]
Hi. That copyright is about Phaser Editor, the tool that generated the json file. You have the copyright of your games even if you are using the free mode of the editor.

I will delete that message from the json file to avoid confusion. Thanks.

**Comment by j2l** [comment]
Thank you, I appreciate you reply quickly.
