### ISSUE TITLE
Add non java included download

### ISSUE THREAD

**Issue by CZHO404** [PhaserEditor2D/PhaserEditor#133]
This is a not really important thing to add but its really easy to implement, i'm having trouble downloading Phaser Editor, the file size is vary lage because of including it.

**Comment by PhaserEditor2D** [comment]
I think it could be confusing for many users and helpful for only a few. If you need help to download the files  just tell me, I can try zipping the file in smaller parts for you.

**Comment by PhaserEditor2D** [comment]
Next web-based version of the editor is going to be less than 20MB :)

**Comment by CZHO404** [comment]
wow thank you so much
