### ISSUE TITLE
Would be great to have an alternative to scrollwheel for zooming the canvas

### ISSUE THREAD

**Issue by tfsJoe** [PhaserEditor2D/PhaserEditor#134]
Would be great to have zoom in and out buttons, and/or another keypress combination to supplement zooming with the scroll wheel. Currently, scrollwheel controls do not work well with some trackpads. For example I can zoom in very easily but struggle to get it to accept a zoom out with my current trackpad.

**Comment by tfsJoe** [comment]
This is on v1.5.4 for Windows.

**Comment by dinostabOMG** [comment]
[Here is a video of an attempt to zoom out using the trackpad.](http://www.trickyfast.com/~jjacir/misc/phasereditor_zoomOutAttempt.mp4)

Please note I recognize that there are several layers to this including device-specific issues, so all I'm suggesting is an alternative rather than a fix.

**Comment by tfsJoe** [comment]
[Here's a video of an attempt to zoom out using the trackpad.](http://www.trickyfast.com/~jjacir/misc/phasereditor_zoomOutAttempt.mp4)

Please note I recognize that there are several layers to this including device-specific issues, so all I'm suggesting is an alternative rather than a fix.

**Comment by PhaserEditor2D** [comment]
Hi, 

Thanks for the video! It is not documented but you can use the `I` and `O` keys to zoom in/out. I just added it to the docs:

https://phasereditor2d.com/docs/canvas.html#common-editing-operations

Please, tell me if it works better with the keys.

**Comment by tfsJoe** [comment]
Ah yes, that works nicely. Thanks!
