### ISSUE TITLE
Icon in Project Explorer shows error, we could use an indication of the specific error.

### ISSUE THREAD

**Issue by tfsJoe** [PhaserEditor2D/PhaserEditor#135]
Hello again, I noticed that in v1.5.4, there are red X icons overlaid on items in the project explorer if they contain errors. For example, we had a canvas with two sprites with the same name, which is an error. However, we had to find it by manually searching because, as far as I know, there is no text display of what the error is.

Would it be possible to get the specific error message or line number in a tooltip when mousing over the item? Or some similar functionality.

Currently, we have a pack.json file showing an error, but we have no idea what it is, for example: 
![image](https://user-images.githubusercontent.com/51897213/60853785-9c0c5e00-a1cb-11e9-8a65-57483170f896.png)

**Comment by PhaserEditor2D** [comment]
Hi, please check in the Problems view if there is any message. If there is an error message, you can double click on it and the Pack Editor should open in the asset key of the problem.

![image](https://user-images.githubusercontent.com/12187299/60856698-0cb87800-a1d6-11e9-8159-da758f5b8107.png)

**Comment by tfsJoe** [comment]
I see, thanks.
