### ISSUE TITLE
How to import js modules to the Phaser Editor

### ISSUE THREAD

**Issue by dedalik** [PhaserEditor2D/PhaserEditor#136]
## Version
* Phaser Editor Version: 2.1.3.20190811
* Operating system: Windows 10

## Description

Hello! Can understand how to import modules to the scene and others `.js` files?

For example, I have `UIScene.js ` and wont to import Constants, from folder:

`import someValue from '../folder';`

and receive the error:
`Uncaught SyntaxError: Cannot use import statement outside a module`.

**Comment by PhaserEditor2D** [comment]
Hi, I was testing this bug. Did you fix it?

**Comment by dedalik** [comment]
Hi, no need to import module throw import, js files in pack.json are in Editor scope.

**Comment by PhaserEditor2D** [comment]
Yes, and are part of the loader progress.
