### ISSUE TITLE
Cannot drag textures to .atlas file

### ISSUE THREAD

**Issue by iamnino** [PhaserEditor2D/PhaserEditor#141]
Currently using PhaserEditor2D with license key.

Steps to replicate: 
Create New "Texture Packer File"
Add name
It will generate <added-name>.atlas file
Select the atlas file 
Drag png images to atlas file. --> Nothing happens.

![image](https://user-images.githubusercontent.com/28583409/72062511-e7d2c800-3312-11ea-917b-5dfb4149eaf8.png)

I've try https://phasereditor2d.com/docs/v2/texture-packer-editor.html

![image](https://user-images.githubusercontent.com/28583409/72063048-f8377280-3313-11ea-94f8-060506aba394.png)

**Comment by PhaserEditor2D** [comment]
Hi, 

Please, what is your OS and Phaser Editor version? I cannot reproduce the error.

**Comment by iamnino** [comment]
Hi.
Currently using MacOS Mojave.
I just download the latest PhaserEditor2D weeks ago.

**Comment by PhaserEditor2D** [comment]
Hi @iamnino 

I should do more testings in macOS, in the meantime, please, let's import the files in another way.

I attach here a patch that I explain later on how to install it.

This is the new way you can import the files.

1. Select the files in the Blocks view.
2. Press the "Import X files" in the Properties view.
3. Saves the editor.

![image](https://user-images.githubusercontent.com/12187299/72165706-f615f800-3395-11ea-86a1-45305476c64b.png)

This is the patch: [patch-TexturePackerEditor-1.zip](https://github.com/PhaserEditor2D/PhaserEditor/files/4046419/patch-TexturePackerEditor-1.zip)

Please, uncompress it and paste the file: `phasereditor.atlas.ui.editor_2.1.5.20191125.jar` in the folder: `PhaserEditor2D/PhaserEditor2D.app/Contents/Eclipse/plugins`. It will replace the old plugin.

Then start the editor. If you don't see the button, then close the editor and start it in the terminal, running the `Debug.sh` file of the `PhaserEditor2D` folder. This is needed to clean the plugins cache.

```
$ cd PhaserEditor2D
$ ./Debug.sh 
```

Please, tell me if it is working for you.
Thanks

**Comment by iamnino** [comment]
Patch works great. Thanks a lot!

**Comment by PhaserEditor2D** [comment]
Good. I will add it to the next release. Thanks.
