### ISSUE TITLE
mouse cursor lost

### ISSUE THREAD

**Issue by mehmetAliAytekin** [PhaserEditor2D/PhaserEditor#142]
hi,
i am using trial edition of ide.
when i save file with ctr+s, mouse cursor gets lost. i have to click file again.
thanks.

## Version

* Phaser Editor Version:

* Operating system:

**Comment by PhaserEditor2D** [comment]
Hi @mehmetAliAytekin 

But what file are you editing? Does it happens in the Scene editor or the JavaScript editor?
What version of Phaser Editor are you using? And OS?

**Comment by mehmetAliAytekin** [comment]
firstly sorry for my missing info.
i'm using windows 10 and it is Phaser Editor 2D - 2.1.5.20191125
i code js (javascript editor).

before editin, cursor is seen.
![image](https://user-images.githubusercontent.com/41567676/72669167-b4ddb200-3a3f-11ea-9e1e-18f6bfa8db92.png)

after coding and ctr+s, it is lost.
![image](https://user-images.githubusercontent.com/41567676/72669175-ccb53600-3a3f-11ea-9af9-1980fab52c25.png)

**Comment by PhaserEditor2D** [comment]
Yes, I can reproduce it. That editor is provided by a third-party plugin: https://github.com/eclipse/wildwebdeveloper

I will update to the latest version of that plugin and check if the bug continues. I should release a new version of the editor this week, to support Phaser 3.22.

**Comment by PhaserEditor2D** [comment]
Fixed.

It is not related to the JS editor. It is related to the browser we use to create the scene screenshots. Yes, it is a bit crazy, but the "offline, hidden" browser gets the focus. 

The fix will be included in the next release, which should be ready in one or two days.
