### ISSUE TITLE
My scene does not work

### ISSUE THREAD

**Issue by GrInPiS** [PhaserEditor2D/PhaserEditor#143]
## Version

* Phaser Editor Version: Phaser Editor 2D - 2.1.6.20200120

* Operating system: Windows 7 Maximum

## Description

My scene does not work. I try to drag a sprite onto it, but it does not drag. In addition, the "grid" of the scene is not visible.

## Possible solution

I don't know how to solve this problem.
![2020-02-11_20-51-01](https://user-images.githubusercontent.com/60938294/74263886-b9307e80-4d10-11ea-8de3-f40436d44f3f.jpg)

**Comment by PhaserEditor2D** [comment]
Hi, probably the Internet Explorer of your system is not supported by the editor.
Can you update your Internet Explorer? In Windows, the editor uses an embedded Internet Explorer in the scene editor. This is a limitation of Eclipse.

This is one of the reasons we are implementing v3 completely for the browser, not as a desktop app.

**Comment by GrInPiS** [comment]
Thanks a lot! I managed to solve the problem of updating the Internet Explorer.

  
>Вторник, 11 февраля 2020, 23:16 +03:00 от Phaser Editor <notifications@github.com>:
> 
>Hi, probably the Internet Explorer of your system is not supported by the editor.
>Can you update your Internet Explorer? In Windows, the editor uses an embedded Internet Explorer in the scene editor. This is a limitation of Eclipse.
>This is one of the reasons we are implementing v3 completely for the browser, not as a desktop app.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Максим Дударев

**Comment by PhaserEditor2D** [comment]
Great!
