### ISSUE TITLE
Game Object Name Not Saved When Scene Is Saved

### ISSUE THREAD

**Issue by Cartrell** [PhaserEditor2D/PhaserEditor#144]
## Version

* Phaser Editor Version:
Phaser Editor 2D - 2.1.6.20200120

* Operating system:
Windows 10 Home 64 Bit

## Description

Hey there,

First, I perform the following steps:
1. Select a game object on the scene
2. Expand the Game Object section from the Properties panel
3. Check the box next to Name
4. Save then close the scene
5. Re-open the Scene, and the Name box is unchecked

![game-object-name-checked](https://user-images.githubusercontent.com/6464920/75097972-dcfc8b80-557e-11ea-825e-0e7deeaf026f.png)
![game-object-name-check-removed-after-save](https://user-images.githubusercontent.com/6464920/75097976-e2f26c80-557e-11ea-9808-b37463a90ed8.png)

## Possible solution

Not sure, but I was looking at src/phasereditor/scene/core/GameObjectComponent.java, and maybe the Name property isn't being save along with the other properties?

**Comment by PhaserEditor2D** [comment]
Hi, I can reproduce this error. I will fix it and send you a patch. Thanks.

**Comment by PhaserEditor2D** [comment]
Fixed.
Please, uncompress this file: 

[patch-2.1.6-issue-144.zip](https://github.com/PhaserEditor2D/PhaserEditor/files/4245274/patch-2.1.6-issue-144.zip)

And replace the `phasereditor.scene.core_2.1.5.20191125.jar` file. It is a patched plugin with the fix.

Close the editor and start it again using the `Debug.bat` file that is present in the root folder of the editor installation. Please tell me if it works for you.

**Comment by Cartrell** [comment]
Looks like the patch is working. I set the names of objects in several scenes, saved, closed, and reopened those scene. The names were saved.

**Comment by PhaserEditor2D** [comment]
Thanks @Cartrell !
I close this. If there is any issue you can open it again. This will be included in the next release.

**Comment by Cartrell** [comment]
Will do. Thanks so much, man!
