### ISSUE TITLE
Images are blury

### ISSUE THREAD

**Issue by Marchiuzzz** [PhaserEditor2D/PhaserEditor#154]
## Version

* Phaser Editor Version: 3.10.2

* Operating system: Windows 10

## Description

When I run the game in Phaser editor all of my images appear to very blurry while in the editor they seem crisp. Why is that? This is the default setup, all I did was add a few images  to the scene
![image](https://user-images.githubusercontent.com/73941456/108183159-7e76d880-7112-11eb-8ed9-3f1152762251.png)

**Comment by PhaserEditor2D** [comment]
The scene editor enables the `pixelArt` flag. You should do the same in your game config:

https://labs.phaser.io/edit.html?src=src/game%20config/pixel%20art%20mode.js&v=3.52.0

```javascript

const config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    pixelArt: true, // look here
    scene: [ Example ]
};

const game = new Phaser.Game(config);
```

**Comment by Marchiuzzz** [comment]
Yup, that was it. Thank you very much!

**Comment by PhaserEditor2D** [comment]
Welcome! Please, keep in contact :)
