### ISSUE TITLE
Some unified tutorial on how to start would be nice

### ISSUE THREAD

**Issue by Marchiuzzz** [PhaserEditor2D/PhaserEditor#156]
I know this is project developed by an independent developer but it's just very frustrating to get started with this tool. All of the tutorials on youtube show completely different ways how to achieve something (let's take movement for example) in some videos I've found that I can basically create player movement in Level.js code while on another tutorial I found that I actually should create a user component and write the logic there, so how do I know which is the right way? I would use the documentation but there's no search function in the V3 docs, from what I saw, earlier docs had the option to search for keywords throughout the documentation. 
![image](https://user-images.githubusercontent.com/73941456/108846598-6c4fdb00-75e7-11eb-9cd5-202391a40668.png)
![image](https://user-images.githubusercontent.com/73941456/108846662-7e317e00-75e7-11eb-987b-158f4bf1ea27.png)

The problem I'm currently stuck with is how do I debug my projects? I get a grey screen when I launch my project in the built-in player, I figured there's a runtime error in my create method but how can I figure out where is it crashing? May I at least know where the errors are output?

**Comment by PhaserEditor2D** [comment]
Hi @Marchiuzzz I invite you to join us in Discord: https://discord.gg/zzPXxr77

**Comment by Marchiuzzz** [comment]
Thanks, hopefully I'll get my answers there
