### ISSUE TITLE
Renaming a scene doesn't copy user code

### ISSUE THREAD

**Issue by DeanoC** [PhaserEditor2D/PhaserEditor#157]
## Version
* Phaser Editor Version: v3.13.0
* Operating system: Windows 10

## Description
When you rename a scene (I use F2 but I presume same from a menu) it creates a new scene with the new name and the widgets but doesn't copy the any user code.

In my case, the means no custom imports at the top of the file and any custom functions assigned in the scene class.

I'm using Typescript if that relevant.

## Possible solution

For now I just manually cut and paste them from the non-renamed .ts file thats still in the folder after the rename.

**Comment by PhaserEditor2D** [comment]
Hi @DeanoC!

When you rename a `.scene` file you also has to rename the `.ts` file. Maybe the IDE can perform certain refactoring and rename the `.ts` file for you, but yet I'm not to convinced to start implementing refactoring tools.
