### ISSUE TITLE
@SeneEditor: Sprite > tint > hex color

### ISSUE THREAD

**Issue by ponderboy** [PhaserEditor2D/PhaserEditor#21]
Hello again,

just as I use it now. It would be practical if one could just paste in a hex value. Now it opens a system color window and I have to put in single rgb values. 
Also, there is not option to just remove the tint again. Once you set it, it's impossible to remove it again. 

Keep up the god work and nice sunday still.

**Comment by boniatillo-com** [comment]
It uses the default color dialog of Windows that is true it does not have the hex format support.

I will think in a better solution, or at least to allow to paste the value directly in the field.

**Comment by boniatillo-com** [comment]
> Once you set it, it's impossible to remove it again.

In the Phaser doc it says "A value of 0xffffff will remove any tint effect". In the editor it is the same, the editor detects if it is set to white and remove the tint.

**Comment by PhaserEditor2D** [comment]
Hi,

> Also, there is not option to just remove the tint again. Once you set it, it's impossible to remove it again.

I forgot to mention that you can do it since v1.4.x, by selecting the property and pressing the `DEL` key.

For the next release, we implemented a cross-platform color dialog where you can use HEX values. Check #55
