### ISSUE TITLE
Animation editor Feature

### ISSUE THREAD

**Issue by aliklev** [PhaserEditor2D/PhaserEditor#32]
Hi.
Are you planning to build timeline visual animator tool for quick and easy  tween or other sprite  animations?
Thank you.

**Comment by boniatillo-com** [comment]
Yes, a tween animation editor is in plan. 

We have a card for it in the development project:

https://github.com/boniatillo-com/PhaserEditor/projects/1

https://github.com/boniatillo-com/PhaserEditor/projects/1#card-1276538

Maybe for v1.5 we can deliver a basic editor for it.

**Comment by boniatillo-com** [comment]
By the way, in the JavaScript code editor you can get a preview of a tween if you hover the mouse on top of an easing constant, like "Elastic", it shows a small preview window with the animation of a ball.

I mention this because in the meantime it can help a bit.

**Comment by PhaserEditor2D** [comment]
Duplicated https://github.com/PhaserEditor2D/PhaserEditor2D-v3/issues/5
