### ISSUE TITLE
Change the Highlightcolor in Chains-Window

### ISSUE THREAD

**Issue by rittimarine** [PhaserEditor2D/PhaserEditor#44]
I've been looking for hours...
Is there a solution to change the syntax highlight color in the chains-window?
All settings under "Window->Preferences" seem to have no influence on this window:
Also the windows 10 - colorsettings have no influence.

![image](https://user-images.githubusercontent.com/19694835/29749928-beec4852-8b36-11e7-9846-7c335087e09a.png)

Your help would be great.

**Comment by samsstuff** [comment]
I thought this was a linux thing only lol
I just lived with it, but looks like this is a dark theme issue instead.
here it is in linux

![dkthemewhite](https://user-images.githubusercontent.com/19275499/29751513-6c3f8af2-8b1c-11e7-9c2b-08459828ec06.png)

Arian this only happens this only happens in chains area where it is the keyword your searching for that this happens, might want to change that in css file, my color picker says it's #E3E3E3, might help you find it quicker ;)
I guess have to find a happy neutral color, how about hot pink?
lol only kidding.
Sam

**Comment by boniatillo-com** [comment]
Hi guys,

Yes I checked and it is coded value. I will add a preference for it, so @samstuff you will be able to set it to pink that is a nice color hehe.

@rittimarine for this release 1.4.2 I will do a workaround to make it to looks better on both light and dark themes. For 1.4.3 I will add the preference parameter together with others.

Thanks.

**Comment by boniatillo-com** [comment]
Ok I will use the LIST_SELECTION_COLOR of the platform, it looks like this:

![image](https://user-images.githubusercontent.com/12187299/29781838-85f86c58-8be8-11e7-9df2-30489854aca0.png)

As I said, in v1.4.3 this could be changed via preferences.

**Comment by rittimarine** [comment]
Great that the implementation was so fast. Many Thanks.

**Comment by boniatillo-com** [comment]
You are welcome :)

I will keep this open until I do the preference page for it.

**Comment by PhaserEditor2D** [comment]
Done, now you can select the colors in `Windows > Preferences > Phaser Editor > Chains`. In the next picture I put some nice colors :), however the default colors remain.

![image](https://user-images.githubusercontent.com/12187299/36232323-5a00f500-11af-11e8-9115-f6cd7c3e2f33.png)

**Comment by rittimarine** [comment]
A great thing.
