### ISSUE TITLE
Check box when create canvas that called "Load on PreloadState"

### ISSUE THREAD

**Issue by PhaserEditor2D** [PhaserEditor2D/PhaserEditor#51]
(from user An Tn)

I have more suggest feature that: sometime I want to load all assets in one State called PreloadState, then I just need load once.
You can think about one check box when create canvas that called "Load on PreloadState" then "load.pack" assets will move to PreloadState.

**Comment by boniatillo-com** [comment]
When you create a project you can select the "Multiple states with Preloader" project structure, it will create the PreloadState for you:

![image](https://user-images.githubusercontent.com/12187299/30919533-ac4aa6c0-a36f-11e7-9914-d4a6c879d7fb.png)

So you can preload more assets by adding the asset pack sections in the Configuration tab:

![image](https://user-images.githubusercontent.com/12187299/30919702-2d15609c-a370-11e7-9198-b36c17841bcc.png)

Note that you can do this for any state, not only a preload state.

**Comment by boniatillo-com** [comment]
You can read about this feature here:

http://phasereditor.boniatillo.com/docs/canvas.html#preloader-state-configuration

**Comment by boniatillo-com** [comment]
Hi @antn9x 

I think I understand now what's the problem. The assets are loaded one time and other in every scene, so I added a new "autoLoad" parameter to the State configuration tab that is "true" by default by you can set it "false". If the autoLoad is disabled then no sections are going to be loaded unless you add it manually to the "pack" property:

![image](https://user-images.githubusercontent.com/12187299/31125276-c583e5a2-a815-11e7-8ce3-124f4cde6d2f.png)

I will add this parameter to the new state wizard too, as you suggested.
