### ISSUE TITLE
Suggest other Color picker

### ISSUE THREAD

**Issue by antn9x** [PhaserEditor2D/PhaserEditor#55]
Current color picker is cannot paste color style like this: "#ebedea". Please improve color picker to us can paste color code easier, may be use JFX color picker?
[](http://docs.oracle.com/javafx/2/ui_controls/color-picker.htm)

**Comment by boniatillo-com** [comment]
For the moment we prefer to use the native color picker. However, maybe the best is to enable the user to use an improved cross-platform color picker or the native color dialog.

Similar issue: https://github.com/boniatillo-com/PhaserEditor/issues/21

**Comment by PhaserEditor2D** [comment]
Now you can select to use the native color dialog or the cross-platform Java Swing dialog:

Just go to `Windows > Preferences > Phaser Editor > Dialogs`

![image](https://user-images.githubusercontent.com/12187299/35302306-f8afa5da-005b-11e8-8461-b95f12e7a5ca.png)

In the cross-platform dialog you have many options, in the RGB tab, you can set the color value using a hex format.

![image](https://user-images.githubusercontent.com/12187299/35302554-dff501ce-005c-11e8-984b-4ae117b3453e.png)
