### ISSUE TITLE
Can't start on MacOS

### ISSUE THREAD

**Issue by mdblabs** [PhaserEditor2D/PhaserEditor#62]
Hi,
I have downloaded last Phaser Editor version for MacOS and it doesn't start. Only error message: "It cannot start". 

I'm running MacOS Sierra. Any idea?

Edit:
More details, about my java version:
java version "1.8.0_111" Java(TM) SE Runtime Environment (build 1.8.0_111-b14) Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Thanks!

**Comment by mdblabs** [comment]
More details, about my java version:
`java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)`

**Comment by boniatillo-com** [comment]
the only thing that comes to my mind is that it is not using the Java bundled with the editor. Let me google a bit.

**Comment by boniatillo-com** [comment]
You just unpacked the zip and clicked on the `Phaser Editor.app`?

**Comment by boniatillo-com** [comment]
Also, try by opening the terminal:

```
cd "/path/to/Phaser Editor.app/Contents/MacOS"
./PhaserEditor
```

**Comment by mdblabs** [comment]
Yep, directly extracted from the zip.
More info: 
```
ls -la
drwx------         102  2 nov 22:41 Phaser Editor.app
-rw-r--r--@       389630204 23 nov 20:18 Phaser-Editor-1.4.3.GA.jre.macosx.zip
```

Trying to execute:
```
./Phaser\ Editor.app/
-bash: ./Phaser Editor.app/: is a directory
```

**Comment by boniatillo-com** [comment]
You cannot execute a directory, you need to go into `Phaser Editor.app/Contents/MacOS` and execute `PhaserEditor`.

**Comment by mdblabs** [comment]
Ok, solved! Was a permissions issue. 
```
ls -la
-rw-r--r--   PhaserEditor
drwx------  jre
./PhaserEditor
-bash: ./PhaserEditor: Permission denied
chmod 755 PhaserEditor
./PhaserEditor
Plugin.start phasereditor.lic...
```
Now I can start it directly from the .app. Thanks!

**Comment by boniatillo-com** [comment]
Oh, that's great!

And how did you add permission? do you think I need to include it in the documentation?

**Comment by boniatillo-com** [comment]
Ah I see, chmod 775

**Comment by mdblabs** [comment]
Normally, you should pack it including permissions. That way, them will be kept over systems. Note: only if packed from a *nix system.

**Comment by boniatillo-com** [comment]
Ok thanks!

**Comment by samvermeirVRT** [comment]
Hi, I just opened the example tanks project and tried to run it but i get this message:

"Exception occurred executing command line.
Cannot run program "/Users/vermeis/Documents/PhaserProjects/Tanks - Example/.project" (in directory "/Users/vermeis/Documents/PhaserProjects/Tanks - Example"): error=13, Permission denied"

any idea what I'm doing wrong?
it's my first time running the editor

**Comment by PhaserEditor2D** [comment]
Hi @samvermeirVRT 

>  and tried to run it but i get this message

Do you mean, the error appears when you open the game in the browser? How do you run the game?

**Comment by samvermeirVRT** [comment]
i mean i open the example and click on the button to run the game. then it opens a dialog box, telling me that it could not run the game. There is an option to see the terminal comment explaining what the error is and thats the error i posted earlier.

Thanks a lot for your fast reply!

**Comment by PhaserEditor2D** [comment]
Hi, maybe the editor is not finding the right browser to launch.

Please, go to Preferences > General > Web Browser and see the browser is configured. You can try to configure a new browser.

Tell me if it works.

![image](https://user-images.githubusercontent.com/12187299/66625671-3f05b700-ebc3-11e9-9952-489744698133.png)
