### ISSUE TITLE
baseClass of prefabs

### ISSUE THREAD

**Issue by DjLeChuck** [PhaserEditor2D/PhaserEditor#63]
Hi, first I will thank you for your Editor, it's a very appreciated tool! 😄 

I don't know if it's a bug or the desired operation but I will explain:
* I create Sprite
* I morph it to button
* I create a prefab from it

Then, the `baseClass` of my prefab is `Phaser.Sprite` instead of `Phaser.Button` (and the same apply with other types).

**Comment by boniatillo-com** [comment]
It is a bug, it should set the `baseClass` to `Phaser.Button`. In the meantime, you can set it manually, not the constructor is using the button parameters, only the `baseClass` is wrong.
