### ISSUE TITLE
Refactoring -> moving assets in pack.json makes canvases unusable.

### ISSUE THREAD

**Issue by PKrawczynski** [PhaserEditor2D/PhaserEditor#64]
So I had a section named "minimal". I moved asset from there to section called lets say "game". 
I moved it in pack editor with action "move" from "minimal" to "game". Canvas file is broken and doesn't show art. It says "missing asset, section: minimal, key: GoblinSpearImage".

How can I point asset to new section (where asset key is the same) without recreating my asset manually and inserting it again in all canvases that use this specific canvas. 

I'd like to have either a way to manually to point to new section (game rather than minimal) since asset name is the same. Or I'd like it to automatically do that for me. 

![image](https://user-images.githubusercontent.com/1142917/33606801-1da97500-d9bf-11e7-99d4-a3cb3e202027.png)

If I could phrase my title better or there is such functionality - I'm really sorry for being dummy.

EDIT: forgot to mention, obviously game debugging/playing/package works perfectly fine since js files are loaded correctly, however "editing" canvases is broken as it doesn't display art and makes it bit harder to design when there are only red boxes on screen :)

**Comment by boniatillo-com** [comment]
Hi i am not un the city i will try to help tomorrow.

**Comment by boniatillo-com** [comment]
Hello @PKrawczynski 

I need to do a better testing of the whole Move refactoring. I plan to do a bug fixing release in the incoming weeks, my recommendation is that you move the assets back to the original section to get the Canvas working again. Then you can create a new section, add the new assets, and in the Assets navigator replace the textures globally:

Please read here: http://phasereditor.boniatillo.com/docs/assets_manager.html#global-replace-texture

Remember to clean the projects if something goes wrong: Project > Clean...

When I back to home we can go deeper in this issue.

**Comment by PKrawczynski** [comment]
Well thats certainly some workaround for now.

Just to clarify - longterm plan is to have "move" action refactor code properly and point prefabs to new sections where assets are found yes?

**Comment by boniatillo-com** [comment]
Hi, I am  back to home. Please unzip the attached file in the `Phaser Editor/plugins` directory. 
It contains 3 files, accept replace them. Restart the editor, the Move operation should work now.

[fixes-64-20171209.zip](https://github.com/boniatillo-com/PhaserEditor/files/1545336/fixes-64-20171209.zip)
