### ISSUE TITLE
Phaser editor doesn't update level

### ISSUE THREAD

**Issue by codingisnothingtodo** [PhaserEditor2D/PhaserEditor#66]
Hi everyone,

Despite I made changes on Level.canvas virtually, level file isn't changed at all. Even after I restart the application, I see updated version of Level.canvas but the level file remains the same.
![level_canvas](https://user-images.githubusercontent.com/17334931/34300910-6906d126-e73b-11e7-8882-79fc9c3c7dc6.PNG)
![levelcode](https://user-images.githubusercontent.com/17334931/34300915-6e5449e2-e73b-11e7-979c-b5c36d5d3375.PNG)

**Comment by PhaserEditor2D** [comment]
Hi. I am con hollydays, i cannot do a real test until next week. Please delete the .ts file and generate it again. To generate it just save the canvas file, por click con the gear button. Also please confirm the ts file is compiled into the js file.

**Comment by codingisnothingtodo** [comment]
Right ts file isn't compiled into js file. Also my imported js project isn't updated when I make changes with canvas editor. But when I create a new project in javascript, canvas editor updates the Level.js. When I create a new Typescript project and run it on browser I get an "favion.ico not found" error, a blank black browser screen. 
I installed TypeScript IDE 1.3.0 on Phaser Editor using Eclipse Marketplace.
I had an error message when I first activate the product. It's about windows registry problem. But I succeed at my second trial. I mention this becuse it may help about the current problem.

**Comment by PhaserEditor2D** [comment]
Ok thanks for mention the error.

So about TypeScript? Is it working now? I wish to provide a better TypeScript programming experience in Phaser Editor v2. We are going to include it by default. Maybe for now you can use `tsc -w`. It executes the compiler in watch mode. Look issue #65

**Comment by PhaserEditor2D** [comment]
Can we close this?

**Comment by codingisnothingtodo** [comment]
Of course. But before closing the issue I want to write down some more experiences. I tried Phaser Editor on Ubuntu. Level.ts file is updated and also js file. But update comes 1 movement back of the virtual editor. For ex I add an image and cannot see it on browser. Then when I added one more image I can see the previous one on browser.

**Comment by PhaserEditor2D** [comment]
I open it again until we get clear of what's happening.

This is how it should work.

- You add an image.
- You save the scene.
- The `Scene.ts` file is updated.
- The `Scene.ts` file should be compiled, manually or by the TS compiler in watch mode.
- Refresh the browser to see the new image.

Is it working to you in that way?

**Comment by PhaserEditor2D** [comment]
By the way, if you are using Firefox, it has some issues with the game refresh. Just open the Dev console and disable caching.

**Comment by codingisnothingtodo** [comment]
When I add an image at visual editor, Level.ts isn't updated and either the Level.js file at my old projects. I created this project before activating the editor. This may be the reason. 
For now, in a newly created Typescript project when I add and image  as the same way Level.ts file is updated but Level.js file isn't. I'll install Typescript and try to compile ts file with "tsc -w" command manually.

**Comment by codingisnothingtodo** [comment]
Today I installed nodejs and typescript. I tried to run typescript compiler with option "tsc --watch" and it works. When I update ts file also js file is updated.

**Comment by PhaserEditor2D** [comment]
That's great, I will close this then. In case you get a new issue you can reopen again.
