### ISSUE TITLE
I get an error at launch

### ISSUE THREAD

**Issue by PhaserEditor2D** [PhaserEditor2D/PhaserEditor#68]
(from user Marc-André)

Hi!

Today I found Phaser Editor, and it looks promising. However, after downloading and unzipping the package for windows, I get an error at launch. This is the content of the log file after running DebugPhaserEditor.bat:
!SESSION Tue Jan 09 15:08:44 EST 2018 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2018-01-09 15:08:44.564
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.RuntimeException: Could not find framework
	at org.eclipse.equinox.launcher.Main.getBootPath(Main.java:1009)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:570)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

Phaser Editor v1.4.4

**Comment by PhaserEditor2D** [comment]
Hi,

please try by downloading it from this link:

https://www.dropbox.com/s/v970crngyp0472q/Phaser-Editor-1.4.4.GA.jre.win64.zip?dl=0

I should create a checksum to validate the downloads.

**Comment by PhaserEditor2D** [comment]
By the way, what tool are you using to unzip?

**Comment by PhaserEditor2D** [comment]
Other  thing you can try is to unzip it to other directory, with a short path, to avoid problems with long filenames. I am looking into other Eclipse users with the same issue and all points it is a unzipping problem.

**Comment by marcantoupin** [comment]
Problem solved! It was caused by Phaser Editor's directory being inside a directory with a name starting with '#'. Unzipping was not the problem (I used windows 7 built-in context menu unzipping, then 7-zip), as Phaser Editor starts properly if I unzip it to that wrong location, then move it elsewhere. Thanks!

**Comment by PhaserEditor2D** [comment]
Great it is working!
