### ISSUE TITLE
A way to handle custom parameters while initializing new states

### ISSUE THREAD

**Issue by blackmoondev** [PhaserEditor2D/PhaserEditor#69]
When starting a new state with game.state.start('newstate', true, false, customParam) there is no way of handling init(customParam) on the newstate.

**Comment by PhaserEditor2D** [comment]
We are going to implement this for the next version. But I will try to implement a patch so you will be able to use this feature before the release.

**Comment by PhaserEditor2D** [comment]
Also, we should do something similar to the constructor of a prefab.

**Comment by PhaserEditor2D** [comment]
Done, now it has an "Arguments" text field where you can write the init method arguments.

![image](https://user-images.githubusercontent.com/12187299/37058794-9dbef8c8-2159-11e8-8b06-b7ca62e90371.png)
