### ISSUE TITLE
Sprite Prefabs do not appear in Assets window or in context menus in Scene files

### ISSUE THREAD

**Issue by ajmetal** [PhaserEditor2D/PhaserEditor#71]
After creating a new Sprite prefab using File -> New -> Sprite Prefab File, the newly created sprite prefab does not appear in the assets window. I've tried adding the corresponding .js file to index.html, adding it the pack file, and restarting the editor but I can't use sprite prefabs.

**Comment by PhaserEditor2D** [comment]
Very strange. Is the file under the `WebContent` folder?

If you add another prefab does it appear? 

Try by cleaning the project: Main menu `Project > Clean... > Clean all project`

**Comment by ajmetal** [comment]
That didn't fix the issue. I'm pretty sure the cause of the problem is that I didn't create the project using File -> New -> Phaser Project. I just added an existing project to the workspace and starting creating canvas files for it. When I compared it with an example project I noticed I was missing the "Javascript Resources" folder.

**Comment by PhaserEditor2D** [comment]
Yes, it could be the problem. 

Please select the project, and click in the  menu `Project > Add Phaser Nature`, it should work.

**Comment by PhaserEditor2D** [comment]
Anyway, is good if you create the projects with the Phaser Project wizard, because it follows the Design/WebContent structure.
