### ISSUE TITLE
Prefab doesn't work

### ISSUE THREAD

**Issue by nuup20** [PhaserEditor2D/PhaserEditor#73]
Tengo un problema con la carga de Prefabs.

Cree un prefab a partir de un grupo, compuesto por dos imagenes. Cuando intento ejecutar la escena con el prefab, deja de funcionar.

**Do you understand spanish language? 

![imagen](https://user-images.githubusercontent.com/29106920/37534568-d191de32-290a-11e8-83e1-27361ceb703a.png)

![imagen](https://user-images.githubusercontent.com/29106920/37534605-eefbdc34-290a-11e8-92e0-904db4833324.png)

**Comment by PhaserEditor2D** [comment]
Hi,

Please look into the Console of the Dev Tool,  it is possible that you are not loading the prefab script in the index.html or pack.json file.

Sí, hablo español, soy cubano, aunque para los issues de github preferiria utilizar el inglés, de esa forma otros pueden colaborar o aprender.

Saludos

**Comment by nuup20** [comment]
thank you, it works now. Ok, my english is really bad, but I'll try!

Saludos!
