### ISSUE TITLE
Support Object names that contain spaces

### ISSUE THREAD

**Issue by puzzud** [PhaserEditor2D/PhaserEditor#77]
It's possible to have spaces in the name of an object contained in the Design screen of a Canvas. However, it produces code that is not syntactically correct.

For example, an object with the name **Start Button** produces the following code:
`var _Start Button =`...

I would expect Phaser Editor to behave similar to how Unity3D Editor handles spaces for object properties:
`var _StartButton =`...

The spaces are absorbed by a camel casing of the first letter of the word afterwards.

**Comment by PhaserEditor2D** [comment]
Camel case is fine, it follows the JavaScript naming conventions.
