### ISSUE TITLE
Special characters in Text object will break code or preview differently than Phaser interprets

### ISSUE THREAD

**Issue by puzzud** [PhaserEditor2D/PhaserEditor#78]
I assume this happens for Text, but I noticed it when using Bitmap Text.

Certain characters in their **text** field value cause issues:

- ' (single quote): The string written out in code to assign a text field value is enclosed with single quotes. A single quote will terminate the string and anything after the single quote will be garbage to the JavaScript interpreter.
- \ (backspace): A backspace will be written out to code and will of course be interpreted as an escape character in a C String fashion. It's possible to escape this character with another one (\\). That will make Phaser Editor's canvas preview of the string to show both characters whereas Phaser will show it differently\-\-therefore, designing and laying out strings will be problematic.

**Comment by PhaserEditor2D** [comment]
Done.

If you like to use the fix then follow this steps:

- Close Phaser Editor.
- Uncompress the ZIP I attach here ([v1.5.1-issue-78-patch-1.zip](https://github.com/PhaserEditor2D/PhaserEditor/files/2043495/v1.5.1-issue-78-patch-1.zip)) and copy the files `phasereditor.canvas.core_1.5.1.20180506.jar` and `phasereditor.project.core_1.5.1.20180506.jar` to the `plugins` folder of your Phaser Editor installation. (Accept replace them)
- Open Phaser Editor and check if the error was fixed.

If you have any problem please tell me.
