### ISSUE TITLE
Cannot control order in which objects under Prefab Group are instantiated

### ISSUE THREAD

**Issue by puzzud** [PhaserEditor2D/PhaserEditor#79]
The order in which objects are listed in a Canvas' list of objects in Design seems to indicate the order in which they are instantiated in code.

The order in which objects are listed in a Prefab Group's list of objects in Design seems to be nearly uncontrollable--after fiddling with it a bit, I could not determine a way to work around this issue. It's using some internal logic to determine order of instantiation.

It would be ideal if this instantiation order was consistent with how it's done directly under a Canvas.

**Comment by puzzud** [comment]
Looking at this further, I suppose Canvas Design object order does not work as I expected either. In which case, I guess this issue is an enhancement request.

I would expect an in-order traversal of the Design Objects tree to determine the order in which all objects are ordered in groups and thus rendered (Z depth).

The Z depth is what is most important to me. It would reduce the amount of grouping and reordering necessary to get the compositing effects I want.

**Comment by PhaserEditor2D** [comment]
I will take a look.

**Comment by PhaserEditor2D** [comment]
Hello @puzzud,

Please, can you show here an image with the wrong order? Look this image I attach here. It shows the order of the objects in a prefab scene and the order in code of the objects of the same scene.

In code, the object in the bottom is created first.

![image](https://user-images.githubusercontent.com/12187299/41553003-795c1d0c-72fe-11e8-9d53-f985fc3d7e61.png)

**Comment by PhaserEditor2D** [comment]
I am trying to reproduce your behavior but I can't. Please can you show an image of your code and scene? I have interest on find the bug or make clear what is happening. If you cannot show an image maybe you can do a small project where the error is reproduced and attach it here.

**Comment by puzzud** [comment]
I'll put together a small project and attach when time permits.

**Comment by PhaserEditor2D** [comment]
Ok thanks.

**Comment by puzzud** [comment]
Added a small project that illustrates this issue:
[TilemapBitmapTextCompositing.zip](https://github.com/PhaserEditor2D/PhaserEditor/files/2142021/TilemapBitmapTextCompositing.zip)

**Comment by PhaserEditor2D** [comment]
Hi @puzzud 

Please, can you tell me what's the problem with that project? I see some Canvas files but I don't know where to look.

Thanks.

**Comment by PhaserEditor2D** [comment]
Hi @puzzud,

We are too busy migrating the editor to Phaser 3, but we are going to do a pause to release a new version of the v1 series. I will take a look at this issue again.

**Comment by PhaserEditor2D** [comment]
@puzzud It is a Phaser Editor bug. The tilemap layer should be added to the prefab group, something like this:

```

function PopupMessage(aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType) {
	
	Phaser.Group.call(this, aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType);
	
... 
	var _map = this.game.add.tilemap('map', 8, 8, this);
	_map.addTilesetImage('tiles');

	var _map_layer = _map.createLayer(0); // actual code, it is wrong!	       
	var _map_layer = _map.createLayer(0, null, null, this); // we should generate this
	_map_layer.resizeWorld();
...
	
}

```

**Comment by PhaserEditor2D** [comment]
Done. Now the layer is added to the prefab group. But also take in consideration that it is fixed to the camera by default, so if you want to move it to other position you should set the fixedToCamera false, or change the `cameraOffset` of the layer.
