### ISSUE TITLE
Asset pack editor: adding image issues

### ISSUE THREAD

**Issue by PhaserEditor2D** [PhaserEditor2D/PhaserEditor#82]
Issue reported by a user in facebook:

Hi I’m using Phaser Editor 1.5.1
Thanks for making good tool 🙂

I have some requests for Assets 

when I add “image” in Asses in Phaser Editor,
“key” name which is added is not include URL path.

is there any solution to add “URL path” to image “key” automatically?

I will attach the image.

thanks!

![assets image](https://user-images.githubusercontent.com/12187299/44341342-a6a7f280-a455-11e8-8bbe-3087ba65f3a2.png)

**Comment by PhaserEditor2D** [comment]
Hi,

> Thanks for making good tool slightly_smiling_face

You are welcome!

> when I add “image” in Asses in Phaser Editor, “key” name which is added is not include URL path.

I do not understand very well your request. When you add an image, by default it set as key the name of the image, without the extension. Like you show in the screenshot, for `assets/images/golem_image/right.png` it uses the key `right`, but you are free to change that name. If you are using the scene editor, we recommend to rename it by pressing F2, it will show the refactoring dialog so scene files will be updated with the new name.

For the moment there is not a way to change this behavior, you have to manually change the key of the image.

For example, here there is the image `logo.png`. I want to change its key to `images/logo.png` so I select the image and press F2. The Rename refactoring dialog is open, so I  write the new key `images/logo.png` and press Continue:

![image](https://user-images.githubusercontent.com/12187299/44341784-f0dda380-a456-11e8-9f73-da2777b41108.png)

The dialog shows the scene files that will be updated, press Continue:

![image](https://user-images.githubusercontent.com/12187299/44341880-41550100-a457-11e8-8b63-af28c6896d43.png)

...and the key is updated, in the pack file and the scenes files:

![image](https://user-images.githubusercontent.com/12187299/44341898-53cf3a80-a457-11e8-81d0-97a4cf9377e8.png)

Does it answer your question? Am I missing something?

**Comment by dirablue** [comment]
Hi, Thank you. I understand I have to change a key manually for now.
I hope new editor version will support the function like this. 
( if there is a lot of files, a bit tough to change name each file )

**Comment by PhaserEditor2D** [comment]
Yes, maybe we can provide an option to include the parent folder in the image (and another type of assets) key.

I will think about it. I keep this as a feature request.

**Comment by PhaserEditor2D** [comment]
Actually, that option could be included in the Texture Packer too, so you can pack the images in an atlas and use the parent folder name as the prefix.

**Comment by PhaserEditor2D** [comment]
I will think if I keep this option in the Asset Pack editor, but I created a new issue (#85) to include this option  (parent folder name as the prefix) in the Atlas Generator editor.

**Comment by dirablue** [comment]
thank you for your support! :)
