### ISSUE TITLE
To  “exclude” image directory in “Pack.json” file

### ISSUE THREAD

**Issue by PhaserEditor2D** [PhaserEditor2D/PhaserEditor#83]
Issue reported by a user in facebook:

I don’t want to load some image files in “Pack.json” function in Phaser Editor since I’m using Spriter animation library.
how can I “exclude” image directory in “Pack.json” screen for these image files?

**Comment by dirablue** [comment]
Hi, thank you for teaching the method.

But this method is a bit different what I wanted to do.
If I hide some images with the filter in Eclipse, I will be not able to see these files in Eclipse.

I want to keep images in Eclipse during developing, but if it's possible I want to avoid adding some images in the target folder when I do "+image" button in "Asset" view.

![image](https://user-images.githubusercontent.com/708452/44345734-54e78280-a4be-11e8-9711-4de1683ddf6f.png)

thanks

**Comment by PhaserEditor2D** [comment]
Thinking about it again, there is another thing you can do.

The Asset Pack editor automatically looks for files in its current folder and sub-folder. So you can create a new folder `assets_outside_pack` in the `WebContent` folder, and add the images there. The pack editor is not going to look for files in that folder, because it is not in the same sub-tree of the `pack.json` file.

![image](https://user-images.githubusercontent.com/12187299/44347411-bfb89f80-a465-11e8-94c0-0c4748cefa79.png)

**Comment by dirablue** [comment]
hi, I see, thank you.
I think I can use this way for animation images.

but I think If I can choose some images to add to "asset", it will be solved.
( because "+image" button is for auto choosing image & adding )

can I choose images to add manually ... ?

**Comment by PhaserEditor2D** [comment]
> but I think If I can choose some images to add to "asset" together, it will be solved.

No, it cannot be done right now, you have to add one by one. I am considering to release a new `1.5.2` version with this feature and others, paid clients are very important to us :)

I am finishing a third report about the Phaser Editor v2 development, after this, we are going to release a new version for the v1 series.

**Comment by dirablue** [comment]
> So, do you think we can close this issue?
yes, thank you so much! :)
