### ISSUE TITLE
Atlas generator editor: an option to Include the parent folder name in the frame names.

### ISSUE THREAD

**Issue by PhaserEditor2D** [PhaserEditor2D/PhaserEditor#85]
Is a common practice, especially on animations, to include the parent folder in the name of the atlas frames.

We should add an option to the Atlas Generator editor to use that naming convention.

**Comment by PhaserEditor2D** [comment]
@dirablue

Done. It will be included in v1.5.2, that is coming very soon.

![image](https://user-images.githubusercontent.com/12187299/44747713-d1d8b480-aadb-11e8-8594-e02532de878d.png)

**Comment by dirablue** [comment]
hi, thank you for updating. it looks nice!
but cannot we use "use folders name" for normal images? ( not atlas type )

thanks

**Comment by PhaserEditor2D** [comment]
Not at the moment, it is targeted in this issue: https://github.com/PhaserEditor2D/PhaserEditor/issues/82#issuecomment-414364482

**Comment by PhaserEditor2D** [comment]
I did not include it in 1.5.2 because you commented "I feel this is not a necessary function for the editor" 

But I added it to 1.5.3, that maybe I release soon, because a bug in macOS with Retina.

**Comment by dirablue** [comment]
ok, thank you ~
