### ISSUE TITLE
UTF8 text error in canvas file

### ISSUE THREAD

**Issue by phidoi247** [PhaserEditor2D/PhaserEditor#89]
Please support UTF-8 encoding in canvas file. After restart IDE or reopen the canvas file, my UTF8 text in its will be changed. 
eg: "Nhất" => "Nhâ?t" in Windows 10
"Tất" => "táº¥t" in MacOS

**Comment by PhaserEditor2D** [comment]
Done. I will release a v1.5.3 with this fix and others. I will upload a version for you to test, before the release.

**Comment by PhaserEditor2D** [comment]
Hi @phidoi247 

Please can you test with the new release:

macOS:

[http://phasereditor2d.com/files/v1.5.3/Phaser-Editor-1.5.3.GA.jre.macosx.zip](http://phasereditor2d.com/files/v1.5.3/Phaser-Editor-1.5.3.GA.jre.macosx.zip)


Windows:

[http://phasereditor2d.com/files/v1.5.3/Phaser-Editor-1.5.3.GA.jre.win64.zip](http://phasereditor2d.com/files/v1.5.3/Phaser-Editor-1.5.3.GA.jre.win64.zip)

**Comment by phidoi247** [comment]
Dear PhaserEditor,

After test, the UTF8 issue of the IDE has been fixed. Thank you for your hard working.

But there are some problems still not fixed. I'm working in a project with about 30 .canvas files. The IDE will be "lag" if i use the "ctrl + space" or copy some code line. So i just use the IDE for design and use Visual Studio Code for coding. Can you fix the "lag" issue of the IDE ?
________________________________
Từ: Phaser Editor <notifications@github.com>
Đã gửi: 08 Tháng Mười Một 2018 7:38 SA
Đến: PhaserEditor2D/PhaserEditor
Cc: phidoi247; Mention
Chủ đề: Re: [PhaserEditor2D/PhaserEditor] UTF8 text error in canvas file (#89)


Hi @phidoi247<https://github.com/phidoi247>

Please can you test with the new release:

macOS:

http://phasereditor2d.com/files/v1.5.3/Phaser-Editor-1.5.3.GA.jre.macosx.zip

Windows:

http://phasereditor2d.com/files/v1.5.3/Phaser-Editor-1.5.3.GA.jre.win64.zip

**Comment by PhaserEditor2D** [comment]
Hi @phidoi247 

That's great that the UTF8 issue is fixed.

Regarding the auto-completion of JavaScript, please, can you open a different issue? We can do some workarounds.
