### ISSUE TITLE
one linux issue chmod in version 2

### ISSUE THREAD

**Issue by samsstuff** [PhaserEditor2D/PhaserEditor#91]
Hello Adrian
long time no see I been busy, went to install the new version but got the old chmod issues
 
chmod: cannot access 'jre/bin/java': No such file or directory
chmod: cannot access 'plugins/phasereditor.resources.executables.linux_*/ffmpeg/ffmpeg': No such file or directory
chmod: cannot access 'plugins/phasereditor.resources.executables.linux_*/ffmpeg/ffprobe': No such file or directory
chmod: cannot access 'plugins/phasereditor.resources.executables.linux_*/optipng/optipng': No such file or directory

the solution I used was just to go into each one and make them all executable by right click on them go to properties then go to permissions and set as executable, I never tried adding the full path in the sh file itself since its just as quick  to just go in and set them all to executables lol

Looks really really nice, havent had time to play with it all yet but so far its great, if I find any issues working in linux other then this I'll post them hopefully with a fix for you and others.
I tested it in linux mint tara

Have a good one :)
Sam

**Comment by PhaserEditor2D** [comment]
Hello @samsstuff !

Nice to hear from you!

The script is working for me. Maybe you executed it outside the PhaserEditor2D folder.

I have good news for you, I am developing the editor mostly on Linux, so things with Linux should go much better this time.

**Comment by samsstuff** [comment]
So far so good for me again and sorry I didnt get right back been working a lot lately, you can close it ,thanks you for this one Adrian been wanting to finally make the switch over to the new phaser :)

**Comment by PhaserEditor2D** [comment]
You are welcome! Hope to see more of your stuff soon or later!
