### ISSUE TITLE
Enable theming and TextMate Dark theme doesn't work on Mac in version 2

### ISSUE THREAD

**Issue by RANUX** [PhaserEditor2D/PhaserEditor#92]
Hello Adrian!
Will be great to switch Phaser Editor V2 to Dark theme.

P.S. Thanks for great work!

**Comment by PhaserEditor2D** [comment]
Hi, we need to do a lot of work on dark themes. At this moment we do not recommend to use them. In macOS, it can create some problems with repaints, for example, in the animations preview controls.

In this version, we recommend using the default theme.

Thanks for the kind words!

**Comment by PhaserEditor2D** [comment]
Fixed for v2.1.0.
