### ISSUE TITLE
Need a way to drag scene canvas on Macbook without mouse (like hand tool in Photoshop)

### ISSUE THREAD

**Issue by RANUX** [PhaserEditor2D/PhaserEditor#94]
Hi!
There is one small issue with dragging scene canvas. I can drag only with mid mouse button :(
How i can bind mid button press to keyboard in Eclipse?
Thanks!

**Comment by PhaserEditor2D** [comment]
No, I don't think you can bind mouse buttons to commands.

I will look at the Photoshop hand tool.

Thanks.

**Comment by PhaserEditor2D** [comment]
Done, you can do this if you keep pressing the `Space` bar. Will be available in the next release.
