### ISSUE TITLE
Add user custom properties in Properties window

### ISSUE THREAD

**Issue by RANUX** [PhaserEditor2D/PhaserEditor#95]
Hi!
If it possible, it would be great to add custom properties in Properties window and auto generating code for them in construct() method,  something like in Unity3d Inspector. It useful for tweaking some constants and config values without coding.
Thanks!

**Comment by PhaserEditor2D** [comment]
Yes, it is something we have to do. What do you think about the `data` property in Phaser v2 and Phaser Editor v1?

https://phasereditor2d.com/docs/canvas.html#user-data

Maybe we can do something similar in v2.

In Phaser v3 there is DataManager we can use too: https://photonstorm.github.io/phaser3-docs/Phaser.Data.DataManager.html

**Comment by RANUX** [comment]
I think `data` property will be useful too, but plain object properties is simpler to use for some constant values without go to code. Or maybe you can add property window for fast editing `json` files. Drag `json` from pack to scene and edit in property window. :)

**Comment by PhaserEditor2D** [comment]
The data property is edited in the same properties editor, you don't need to go to code. But we have to think in something more friendly, more common like simple key/values, that you can even change in many objects at the same time.

**Comment by PhaserEditor2D** [comment]
Hi,

Done. There is a new Game Object section in the Properties view. There you can add custom properties. If you defined other properties in the scene, then it will show a menu with when you can select to add one of those properties. Note each property has a menu. That menu contains the options of select all the objects that use the property or all the objects with the same property/value pair, and the option to remove the property.

The scene compiler will generate a `sprite.setData('propertyName', value)` for each property you define. Attention! The value of a property is verbatim generated. It means, if you want to assign a string value you should write `"the value"` (quoted). This allows you to use any expression as a value, like a variable, a JSON object, a Phaser constant, whatever you need.

Look for the `setData()` method in the Phaser docs: https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.GameObject.html#setData__anchor

This is the minimum we can do to allow custom properties. This should be improved with the introduction of prefabs.

![image](https://user-images.githubusercontent.com/12187299/52084682-96518300-2570-11e9-82ce-f0e245d43391.png)

![image](https://user-images.githubusercontent.com/12187299/52084687-99e50a00-2570-11e9-94e8-7ad76ee56fba.png)
