### ISSUE TITLE
Add setVisible and setActive checkboxes to Properties window

### ISSUE THREAD

**Issue by RANUX** [PhaserEditor2D/PhaserEditor#96]
Hi!
It will be useful to set active, visible in Properties window for text or sprites.
Thanks!

**Comment by PhaserEditor2D** [comment]
Done.

A new Game Object section was added. It provides two buttons in the toolbar, to check/uncheck the `enable` and `visible` properties. When `visible=false`, the object is rendered with certain transparency, in the scene editor, do you think is it fine?

There are other properties that we need to add to this section, like `setInteractive` and `data`, but we are going to do it as a different task. BTW, the `data` property could help with the custom properties issue: https://github.com/PhaserEditor2D/PhaserEditor/issues/95.

![image](https://user-images.githubusercontent.com/12187299/51424957-90889480-1ba3-11e9-92dd-c5d249409d65.png)
