### ISSUE TITLE
Shortcut to duplicate entities in scene

### ISSUE THREAD

**Issue by sathyarajshetigar** [PhaserEditor2D/PhaserEditor#98]
Please add a shortcut to duplicate entities in the scene like how Unity does with Ctrl+D.

**Comment by RANUX** [comment]
You can duplicate with Ctrl+C (Cmd+C on mac) and then past with Ctrl+V (Cmd+V). 
I think, Ctrl+D (Cmd+D on mac) will be useful too:)

**Comment by sathyarajshetigar** [comment]
Yes. Coming from Unity background It makes lot of sense with Ctrl+D

**Comment by PhaserEditor2D** [comment]
We are going to implement a duplicate command for the next minor release.

**Comment by PhaserEditor2D** [comment]
Done, in the next version, you will be able to duplicate the selected objects by pressing `Ctrl/Commad+D` (you can change this in Preferences). 

In addition, you can click on the "Duplicate" icon in the "Editor" section of the Properties view:

![image](https://user-images.githubusercontent.com/12187299/51346023-8fa01780-1a6a-11e9-97f2-9a3cf697004a.png)
